---
abstract: 'proxy requests'
author:
  - 'Lee Aylward'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IO::Socket::INET: 0
  Test::More: 0.88
  Test::Requires: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Proxy
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::HTTP: 1.44
  HTTP::Headers: 0
  Plack: 0.9913
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/leedo/Plack-App-Proxy.git
version: 0.16
